@startuml

title __CONSTANTS's Class Diagram__\n

  namespace Constants {
    class Constants.Constants {
        {static} + AGENT_HEIGHT : int
        {static} + AGENT_WIDTH : int
        {static} + BOARD_HEIGHT : int
        {static} + BOARD_WIDTH : int
        {static} + CITIES : String[]
        {static} + CITY_COST : int
        {static} + CITY_SIZE : int
        {static} + COMPUTER_X : int
        {static} + COMPUTER_Y : int
        {static} + DICE_HEIGHT : int
        {static} + DICE_SIZE : int
        {static} + DICE_WIDTH : int
        {static} + DICE_X : int
        {static} + DICE_Y : int
        {static} + DIR_AGENT : String
        {static} + DIR_DICE : String
        {static} + DIR_RESOURCE : String
        {static} + DIR_STRUCTURE : String
        {static} + DIR_TILE : String
        {static} + END_FONT : Font
        {static} + FONT_TYPE : Font
        {static} + MAINFRAME_HEIGHT : int
        {static} + MAINFRAME_TITLE : String
        {static} + MAINFRAME_WIDTH : int
        {static} + MAX_BALANCE : int
        {static} + PLAYER_X : int
        {static} + PLAYER_Y : int
        {static} + TILE_HEIGHT : int
        {static} + TILE_PADDING : int
        {static} + TILE_SEQ : int[][]
        {static} + TILE_WIDTH : int
    }
  }
  

  namespace Constants {
    enum CITY_STATE {
      free
      owned_by_computer
      owned_by_player
    }
  }
  

  namespace Constants {
    enum TILE_TYPE {
      computer
      free
      island
      none
      player
      start
    }
  }
  

  Constants.Constants +-down- Constants.Constants.CITY_STATE
  Constants.Constants +-down- Constants.Constants.TILE_TYPE


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
